// THIS IS AUTO-GENERATED CLASS DEFINITION
// DO NOT EDIT THIS FILE
// IF YOU ARE NOT AWARE OF WHAT YOU ARE DOING

using System;
using System.Collections.Generic;
using System.Windows.Controls;
using Excel = Microsoft.Office.Interop.Excel;

namespace tablesharp
{
  class Item
  {
    // Define properties of each item
    public string Category { get; set; }
    public string FieldName { get; set; }
    public string Description { get; set; }
    public int Size { get; set; }
    public bool IsPublic { get; set; }
    public string Comment { get; set; }

    // Define Header and input type for each property
    // Header will be shown in table editing scene and exported spreadsheet
    // If a property shall support multiline text, use `InputType.Multiline`
    // If a property shall support yes/no or true/false, use `InputType.Checkbox`
    // Otherwise, `InputType` argument is not required
    private static readonly Dictionary<string, Property> itemTypes = new Dictionary<string, Property>
    {
      { "Category", new Property("Category") },
      { "FieldName", new Property("Field name") },
      { "Description", new Property("Description", InputType.Multiline) },
      { "Size", new Property("Size") },
      { "IsPublic", new Property("Public") },
      { "Comment", new Property("Comment", InputType.Multiline) },
    };

    // Define item constructor
    public Item(string category, string fieldname, string description, int size, bool ispublic, string comment)
    {
      Category = category;
      FieldName = fieldname;
      Description = description;
      Size = size;
      IsPublic = ispublic;
      Comment = comment;
    }

    // Define default value for each property
    public Item()
    {
      Category = "";
      FieldName = "";
      Description = "";
      Size = int.MinValue;
      IsPublic = true;
      Comment = "";
    }

    public static Tuple<int, int> FillHeader(Excel.Range cells, Tuple<int, int> addr)
    {
      int row = addr.Item1;
      int col = addr.Item2;
      Excel.Range start = cells[row, col];
      cells[row, col].EntireRow.Font.Bold = true;
      cells[row, col++] = "Category";
      cells[row, col++] = "Field name";
      cells[row, col++] = "Description";
      cells[row, col++] = "Size";
      cells[row, col++] = "Comment";
      Excel.Range end = cells[row, col - 1];
      cells.Range[start, end].BorderAround2();
      return new Tuple<int, int>(row, col);
    }

    public Tuple<int, int> FillRow(Excel.Range cells, Tuple<int, int> address)
    {
      int row = address.Item1;
      int col = address.Item2;
      Excel.Range start = cells[row, col];
      cells[row, col++] = Category;
      cells[row, col++] = IsPublic ? FieldName : "Reserved";
      cells[row, col++] = IsPublic ? Description : "";
      cells[row, col++] = Size;
      cells[row, col++] = Comment;
      Excel.Range end = cells[row, col - 1];
      cells.Range[start, end].BorderAround2();
      return new Tuple<int, int>(row, col);
    }

    // DO NOT EDIT BELOW
    public static void OnAutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
    {
      Helper.OnAutoGeneratingColumn(sender, e, itemTypes);
    }
  }
}